init:
  target:
    URL: ssh://127.0.0.1
    Credentials: localhost
  appPath: $WorkingDirectory(./..)
  Ver: $Cat(${appPath}/Version)

pipeline:
  set_sdk:
    action: sdk.set
    target: $target
    sdk: go:1.17
  build:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - cd ${appPath}/scy
      - export GOOS=linux
      - export GOARCH=amd64
      - go build -ldflags="-X 'main.Version=${Ver}'" -trimpath
      - tar cvzf scy_linux_amd64_${Ver}.tar.gz scy
      - export GOOS=darwin
      - go build -ldflags="-X 'main.Version=${Ver}'" -trimpath
      - tar cvzf scy_darwin_amd64_${Ver}.tar.gz scy
      - export GOOS=darwin
      - export GOARCH=arm64
      - go build -ldflags="-X 'main.Version=${Ver}'" -trimpath
      - tar cvzf scy_darwin_arm64_${Ver}.tar.gz scy
   